### ISSUE TITLE
Add support for div and span attributes

### ISSUE THREAD

**Issue by Witiko** [Witiko/markdown#126]
Since version 2.15.0 (#91), Markdown has had renderers for attributes and attribute contexts. However, the Lua parser only supports attributes on headings and not on other elements such as [divs and spans][1]. Future development should start by adding support for div and span attribute renderers to TeX.

 [1]: https://pandoc.org/MANUAL.html#divs-and-spans

**Comment by Witiko** [comment]
See https://github.com/jgm/lunamark/pull/36, which implements both syntax extensions to jgm/lunamark. Perhaps we can backport the syntax extensions to markdown?

**Comment by Witiko** [comment]
[The `slice` option][1] should work not just for headings but also for divs.

 [1]: https://witiko.github.io/markdown/#slice

**Comment by Witiko** [comment]
### Tasks

- [ ] Port *fenced divs* and *bracketed spans* (see also [Pandoc documentation][2]) syntax extensions from [jgm#36][1].
- [ ] Double-check the [user manual examples for the header attribute context renderers][3].
- [ ] Add *fenced div attribute context* and *code span attribute context* renderers.
- [ ] Add `fencedDivs` and `bracketedSpans` Lua options.
- [ ] Add unit tests for [*fenced divs*][4] and [*bracketed spans*][5].
- [ ] For *fenced divs*, make the `slice` Lua option work as it does for headings.
- [ ] Add unit tests that test the interplay between the `fencedDivs` and `slice` Lua options.

 [1]: https://github.com/jgm/lunamark/pull/36
 [2]: https://pandoc.org/MANUAL.html#divs-and-spans
 [3]: https://witiko.github.io/markdown/#header-attribute-context-renderers
 [4]: https://github.com/jgm/lunamark/pull/36/files#diff-5fb2154f296ca8ff1b7f894e3538b512f889876cdb439fae78dd5c513573a5b4R3-R9
 [5]: https://github.com/jgm/lunamark/pull/36/files#diff-7027d9dae0bc4dd87c8f08bad12cbf696c6636e26101b03055824af82062ba36R3-R13
