### ISSUE TITLE
Make tinyyaml a standalone CTAN package

### ISSUE THREAD

**Issue by zepinglee** [Witiko/markdown#218]
I'm planning to add CSL-YAML support for the citeproc-lua project ([citeproc-lua/pr#29](https://github.com/zepinglee/citeproc-lua/pull/29)) and I find the tinyyaml parser inside the `markdown` package very useful. This module is also required by @kalekje's [yamlvars](https://www.ctan.org/pkg/yamlvars). Is is ok to upload the YAML parser as a standalone package to ctan/texlive which would simplify the package dependencies.

**Comment by Witiko** [comment]
That would be appreciated. Please, let me know when you have released the package, so that I can use it to replace the `markdown-tinyyaml.lua` module shipped with the Markdown package.

**Comment by Witiko** [comment]
> citeproc-lua project

What a cool project. Is it supposed to be a CSL-supporting replacement of BibLaTeX?

> Is is ok to upload the YAML parser as a standalone package to ctan/texlive which would simplify the package dependencies.

That would be appreciated. Please, let me know when you have released the package, so that I can use it to replace the `markdown-tinyyaml.lua` module shipped with the Markdown package.

**Comment by Witiko** [comment]
@texhackse We may replace the `markdown-tinyyaml.lua` file with a standalone package (likely without the `markdown-` prefix) in the near future. If I recall correctly, you were using `markdown-tinyyaml` in your projects.

**Comment by TeXhackse** [comment]
That's not an issue. I have mappings there testing before that tinyyaml is found. The project we had was yamlvars, which was already mentioned.

**Comment by zepinglee** [comment]
> What a cool project. Is it supposed to be a CSL-happy replacement of BibLaTeX?

Thanks! It's another approach of citation formatting.

> That would be appreciated. Please, let me know when you have released the package, so that I can use it to replace the `markdown-tinyyaml.lua` module shipped with the Markdown package.

Sure.

**Comment by Witiko** [comment]
@zepinglee Have you got any news on this front?

**Comment by zepinglee** [comment]
I'm a little stuck with it. The `api7/lua-tinyyaml` only supports a subset of the YAML feature and it fails to parse several CSL-YAML items exported from Zotero. This is very likely to cause bugs to end users. I've made several patches to the project but they are still not enough. I'm not sure if I should go on with the YAML feature for citeproc-lua as well as maintaining a CTAN pakcage.

**Comment by Witiko** [comment]
@zepinglee Can you open issues in the api7/lua-tinyyaml repository for the remaining issues that you have identified? I and the other contributors can help tackle them. When you are happy with the code, I can release the updated library as part of the Markdown package (`markdown-tinyyaml.lua`) and we can start worrying about a CTAN release.

**Comment by zepinglee** [comment]
I've uploaded the `lua-tinyyaml` to CTAN (<https://ctan.org/pkg/lua-tinyyaml>). It can be loaded via `require("tinyyaml")`.

Sadly the api7 team does not plan to implement the full features of YAML because tinyyaml already meets their needs. I've fixed several bugs to make it work in most cases of citeproc-lua and CSL.

**Comment by Witiko** [comment]
Well done, thank you for letting us know! I will reopen this issue until we've started `tinyyaml` in the Markdown package. We will need to try loading `tinyyaml` and fall back on `markdown-tinyyaml` if unavailable (in historic images). This is currently blocked by #281. After we have dropped support for TeX Live 2022, we can safely remove `markdown-tinyyaml.lua` completely by manually reverting parts of https://github.com/Witiko/markdown/pull/77/commits/a2d1a6431ebc0c4179de238bc62507b7b0bacee8 and https://github.com/Witiko/markdown/pull/77/commits/8e6ee247e0599b38eba0fa5cf21957b33234d905.

**Comment by Witiko** [comment]
### Tasks

- [ ] Update `libraries/tinyyaml` submodule.
- [ ] Add a TODO in `markdown.dtx` for replacing `require("markdown-tinyyaml")` with `require("tinyyaml")` after we have dropped support for TeX Live 2023.
- [ ] Update `CHANGES.md` (section Libraries).

**Comment by Witiko** [comment]
Hi @zepinglee,

With version 3.9.0 of the Markdown Package for TeX, we dropped support for TeX Live 2022 and switched from distributing `markdown-tinyyaml.lua` ourselves to relying on your `tinyyaml.lua` on CTAN.

However, the CTAN version still lists v0.4.3 and does not include:
- The official v0.4.4 release, which adds support for arrays of multi-line strings (less critical for our use case), and
- The latest commit from January 9, 2024 (https://github.com/api7/lua-tinyyaml/commit/197632c5aca09321ed89ed975613e7c16c7aaa00), which adds support for nested numbers. 

The nested numbers feature is especially important to us because the Markdown Package for TeX is type-sensitive and `[1, 2, 3]` would be processed differently from `["1", "2", "3"]`. Would you be open to publishing an updated version on CTAN? You might consider labeling it something like `v0.4.4-1-g197632c` (from `git describe --tags --always --long`) to distinguish it from the official v0.4.4 release.

Thanks again for maintaining `tinyyaml`!

**Comment by Witiko** [comment]
@zepinglee: Please, let me know what you think. Unless we can keep the CTAN package up-to-date, I will vend in the library tinyyaml again and distribute it with the Markdown package as `markdown-tinyyaml.lua` after the February 3.11.0 release.

**Comment by Witiko** [comment]
@zepinglee: Thanks for the update!

![Image](https://github.com/user-attachments/assets/70a29e5e-60ee-4a5d-80ec-0bfafc96f9a8)

I am closing this issue.
