### ISSUE TITLE
Unify how Pandoc syntax extensions are named and cited in documentation

### ISSUE THREAD

**Issue by Witiko** [Witiko/markdown#274]
In the technical documentation, we currently use two different naming schemes for Pandoc syntax extensions:
https://github.com/Witiko/markdown/blob/36290d5c75687462734a3d7fac29b4bdd90659a5/markdown.dtx#L3663-L3667
https://github.com/Witiko/markdown/blob/36290d5c75687462734a3d7fac29b4bdd90659a5/markdown.dtx#L6770-L6771
We should unify the naming in favor of the top example. To disambiguate the Pandoc syntax extensions, we should also add links to https://pandoc.org/MANUAL.html.

### Tasks
- [ ] Unify the naming of Pandoc syntax extensions.
- [ ] Link Pandoc syntax extensions to https://pandoc.org/MANUAL.html.
- [ ] Replace `Pandoc's` with `Pandoc`:
https://github.com/Witiko/markdown/blob/36290d5c75687462734a3d7fac29b4bdd90659a5/markdown.dtx#L24908
- [ ] Replace trailing colons in `false` branches of Lua option documentation:
https://github.com/Witiko/markdown/blob/36290d5c75687462734a3d7fac29b4bdd90659a5/markdown.dtx#L3671
https://github.com/Witiko/markdown/blob/36290d5c75687462734a3d7fac29b4bdd90659a5/markdown.dtx#L5612
https://github.com/Witiko/markdown/blob/36290d5c75687462734a3d7fac29b4bdd90659a5/markdown.dtx#L7418

This issue is blocked by #256 and #270.
