### ISSUE TITLE
Move `\markdownSetup` from LaTeX layer to plain TeX + expl3 layer

### ISSUE THREAD

**Issue by Witiko** [Witiko/markdown#275]
The `\markdownSetup` and `\setupmarkdown` commands of LaTeX and ConTeXt are close duplicates and mostly just wrappers for functionality provided by the plain TeX + expl3 layers (see a recent [layer diagram of the Markdown package][2]):

https://github.com/Witiko/markdown/blob/36290d5c75687462734a3d7fac29b4bdd90659a5/markdown.dtx#L17860-L17869
https://github.com/Witiko/markdown/blob/36290d5c75687462734a3d7fac29b4bdd90659a5/markdown.dtx#L19031-L19044

We should move most of the heavy lifting to the plain TeX + expl3 layer and make the `\markdownSetup` command available from plain TeX. This will deduplicate the code and make it possible to use the `\markdownSetup` command uniformly across all formats with all its benefits (#232).

### Tasks

- [ ] Replace `markdown/latex-options` and `markdown/context-options` keyvals with a single `markdown/options` keyval defined in the plain TeX layer.
- [ ] In ConTeXt, redefine `\@@_set_option_value:nn` to include the special handling of values `yes` and `no`:
https://github.com/Witiko/markdown/blob/36290d5c75687462734a3d7fac29b4bdd90659a5/markdown.dtx#L19114-L19124
- [ ] In ConTeXt, add new entries to the `markdown/options` keyval using just the `\@@_caseless:N` function:
https://github.com/Witiko/markdown/blob/36290d5c75687462734a3d7fac29b4bdd90659a5/markdown.dtx#L19093-L19102
- [ ] In LaTeX, define `theme` and `snippet` keys for the `markdown/options` keyval:
https://github.com/Witiko/markdown/blob/36290d5c75687462734a3d7fac29b4bdd90659a5/markdown.dtx#L18120-L18124
https://github.com/Witiko/markdown/blob/36290d5c75687462734a3d7fac29b4bdd90659a5/markdown.dtx#L18451-L18462
- [ ] Move code for defining renderers and renderer prototypes from LaTeX layer to the plain TeX + expl3 layer:
https://github.com/Witiko/markdown/blob/36290d5c75687462734a3d7fac29b4bdd90659a5/markdown.dtx#L18713-L18845
- [ ] Rewrite unit tests to use `\markdownSetup` exclusively.

 [2]: https://github.com/Witiko/markdown/issues/215#issuecomment-1359250887
