### ISSUE TITLE
Add support for universal (cross-format) themes

### ISSUE THREAD

**Issue by Witiko** [Witiko/markdown#276]
Since version 2.10.0 of the Markdown package, we have supported [LaTeX themes and snippets][1]. We should move the concepts of themes and snippets from the LaTeX layer to the plain TeX + expl3 layer (see a recent [layer diagram of the Markdown package][2]). On-disk, a theme would correspond to different files for different TeX formats. For example, the theme `witiko/markdown/example` would load the following files in different formats:

- `markdownthemewitiko_markdown_example.tex` in plain TeX
- `markdownthemewitiko_markdown_example.sty` in LaTeX
- `t-markdownthemewitiko_markdown_example.tex` in ConTeXt
- `markdownthemewitiko_markdown_example.opm` in OpTeX (blocked by #215)

This architecture enables the creation of *universal* (aka *fat*) Markdown themes that work across different TeX formats. Formats without their format-specific theme would fall back to the plain TeX theme and issue a warning.

Besides the utility of universal themes for third parties, who can use Markdown as a unifying framework on top of different TeX formats, universal themes also present opportunities for simplifying the architecture of the Markdown package itself: We can neatly package all the default definitions of renderer prototypes as a single universal theme `witiko/markdown/defaults`, which could become its own independent TeX package in the future similar to [lt3luabridge][3]. We can also simplify the architecture of unit tests by merging files `markdownthemewitiko_markdown_test.sty` and `plain-setup.tex` into a universal theme `witiko/markdown/test`.

This issue is currently blocked by #275.

 [1]: https://www.tug.org/TUGboat/tb42-2/tb131novotny-markdown.pdf
 [2]: https://github.com/Witiko/markdown/issues/215#issuecomment-1359250887
 [3]: https://ctan.org/pkg/lt3luabridge

**Comment by Witiko** [comment]
### Tasks

- [ ] Move the `code`, `import`, `snippet`, and `theme` options from LaTeX to plain TeX.
- [ ] Add the `\markdownSuper` command, which loads the plain TeX theme from the ConTeXt / LaTeX (/ OpTeX) theme, if it exists.
- [ ] Move default LaTeX, ConTeXt(, and OpTeX) renderer (prototype) definitions to a new theme `witiko/markdown/defaults`.
- [ ] Merge files `plain-setup.tex` and the LaTeX theme `witiko/markdown/test` into the plain TeX theme with the same name.
