### ISSUE TITLE
Remove deprecated parts before 3.0.0

### ISSUE THREAD

**Issue by Witiko** [Witiko/markdown#309]
After merging #226, we should remove all deprecated parts of `markdown.dtx`.

### Tasks

- [x] Remove `hardLineBreaks` Lua option.
    - [x] Add and document `softLineBreak` renderer and renderer prototype.
    - [x] Remove support for `lineBreak` renderer and renderer prototype.
    - [x] Update unit tests.
- [x] Remove `inlineFootnotes` Lua option.
- [x] Remove `footnotes` Lua option.
    - [x] Remove support for `footnote` renderer and renderer prototype.
- [x] Remove `helperScriptFileName` plain TeX option.
- [x] Remove `outputTempFileName` plain TeX option.
- [x] Remove `errorTempFileName` plain TeX option.
- [x] Change the semantics of `headerAttributeContextBegin` and `End` renderers.
- [x] Remove support for `horizontalRule` renderer and renderer prototype.
- [x] Remove `\markdownMode` plain TeX command.
- [x] Remove `\markdownLua{Unregister,Register}IBCallback` plain TeX command.
- [x] Remove `theme` LaTeX option deprecation notice.
- [x] Remove Lua shell escape bridge.
