### ISSUE TITLE
The parser does not parse the full ISTQB example document

### ISSUE THREAD

**Issue by Witiko** [Witiko/markdown#345]
Consider the [document `example-istqb-content.md`][1]. The document contains a number of sections, but only the first paragraph of the document is recognized by the parser of Markdown 3.0.0:

```
$ docker run --rm -it -v "$PWD":/mnt -w /mnt witiko/markdown:3.0.0-0-gdcaea6c-latest markdown-cli example-istqb-content.md
\markdownRendererDocumentBegin
\markdownRendererSectionBegin
\markdownRendererHeadingOne{Fundamentals of Testing}\markdownRendererInterblockSeparator
{}\markdownRendererSectionBegin
\markdownRendererHeadingTwo{Showcase of the LaTeX template for ISTQB documents}\markdownRendererInterblockSeparator
{}\markdownRendererSectionBegin
\markdownRendererHeadingThree{Regular text}\markdownRendererInterblockSeparator
{}Regular parapgraphs and senteces are written without any formatting. New line is depited by two spaces at the end of the line and a new line.\markdownRendererParagraphSeparator
{}
\markdownRendererSectionEnd 
\markdownRendererSectionEnd 
\markdownRendererSectionEnd \markdownRendererDocumentEnd
```

This issue is likely linked to the addition of TeX-like rich paragraphs in https://github.com/Witiko/markdown/pull/306. Closing this issue will allow us to continue work on https://github.com/danopolan/istqb_latex/pull/77.

 [1]: https://github.com/danopolan/istqb_latex/blob/65c4d0fdecce1d8492cc7eba4bc7738b29cda60b/example-istqb-content.md

**Comment by Witiko** [comment]
Here is a minimal working example document `example.md`, notice the single trailing space at the end of the second paragraph:

``` md
Here is the first paragraph.

Here is the second paragraph. 

Here is the third paragraph.
```

Here is the result of running `markdown-cli example.md`:

``` tex
\markdownRendererDocumentBegin
Here is the first paragraph.\markdownRendererParagraphSeparator
{}\markdownRendererDocumentEnd
```

The expected behavior is that three paragraphs are recognized.

Removing the trailing space produces the correct output:

``` tex
\markdownRendererDocumentBegin
Here is the first paragraph.\markdownRendererParagraphSeparator
Here is the second paragraph.\markdownRendererParagraphSeparator
Here is the third paragraph.\markdownRendererDocumentEnd
```

This issue seems to target the blind spot of our unit tests: When writing inline markdown, no TeX engine other than ConTeXt can recognize trailing spaces. Since the unit tests expect the same results for inline markdown and when inputting markdown documents using the `\markdownInput` command (or using Lua as in this issue), the behavior of trailing spaces are not tested.

As the next step, we should try to reproduce the error using a commit before merging #306 to see if the error has been introduced by #306.

**Comment by Witiko** [comment]
Regardless, we may want to add support for YAML blocks at the top of testfiles that would allow us to specify whether a testfile should be processed for a given format or template. For example:

``` yaml
if: format == 'context' or template == 'input'
```

This would allow us to test the behavior of trailing spaces even though they cannot be processed by some formats and templates.

**Comment by Witiko** [comment]
> As the next step, we should try to reproduce the error using a commit before merging #306 to see if the error has been introduced by #306.

I tried to reproduce the error using the Docker image `witiko/markdown:3.0.0-alpha.2-120-gd4acce2-latest` from commit d4acce2 before merging #306. Here is the result of running `markdown-cli example.md`:

``` tex
Here is the first paragraph.\markdownRendererInterblockSeparator
{}Here is the second paragraph.\markdownRendererInterblockSeparator
{}Here is the third paragraph.\markdownRendererDocumentEnd
```

This indicates that the error has been introduced by #306.

**Comment by Witiko** [comment]
### Tasks

- [ ] Fix the parsing of document `example.md` from https://github.com/Witiko/markdown/issues/345#issuecomment-1700952575.
- [ ] Add a regression test for the issue:
    - [ ] Add and document support for YAML blocks in testfiles, as described in https://github.com/Witiko/markdown/issues/345#issuecomment-1704050058.
    - [ ] Enable special treatment of trailing spaces in tests for ConTeXt MkIV by removing the following lines:
          https://github.com/Witiko/markdown/blob/c1af40672e26eea5e041df840a1c881da42e4103/tests/templates/context-mkiv/verbatim/body.tex.m4#L7-L8
    - [ ] Add a test `hard-line-breaks.test`, as described in https://github.com/Witiko/markdown/issues/345#issuecomment-1704050058. Ensure that the test also acts as a regression test for this issue by testing e.g. that trailing spaces at the end of a paragraph do not produce a hard line break.

### Nice to haves

- [ ] Find all CommonMark examples that test the behavior of trailing tabs and spaces and add them as testfiles that only run with the ConTeXt MkIV format or with the `verbatim` template.
- [ ] Add and document optional fields `title`, `author`, and `date` to YAML blocks. Display these fields in addition to the name of a testfile in `test.py`.
