### ISSUE TITLE
Add support of bulk redefinition of token renderers and token renderer prototypes in the `\markdownSetup` command using enumeration

### ISSUE THREAD

**Issue by Witiko** [Witiko/markdown#362]
Continues #232 and #361.

### Tasks

- [x] Either parametrize `\g_@@_glob_cache_prop` with a sequence name or hardcode the sequence `\g_@@_renderers_seq`.
- [x] Document that not just wildcards but also enumeration are supported and add an example for both.
- [x] Make it possible to recover the renderer (prototype) name from the definition using `#0`.
      Here is how this can be done in expl3:

   ``` tex
   \input expl3-generic
   \ExplSyntaxOn
   \tl_set:Nn \l_tmpa_tl { #0~#1! }
   \regex_replace_all:nnN { \cP\#0 } { Hello } \l_tmpa_tl
   \cs_generate_variant:Nn \cs_new:Nn { NV }
   \cs_new:NV \hello:n \l_tmpa_tl
   % Leave the text "Hello world!" in the input stream.
   \hello:n { world }
   \bye
   ```

   Document this possibility and add an example.

- [x] Use enumeration and wildcards in tests (file `keyval-setup.tex`) in addition to the technical documentation.
