### ISSUE TITLE
Add support for TeX Live 2024 pretest

### ISSUE THREAD

**Issue by Witiko** [Witiko/markdown#404]
TeX Live 2024 pretest is underway [tug.org: [index][3] / [mirrors][5] / [plan][6], [twitter][4]]. We should test the Markdown package with it!

### Tasks

- [x] ~~Add capybara to the list of runners, as discussed with @TeXhackse on [matrix.org][1].~~
- [x] ~~Set up a daily build of TeX Live 2024 pretest Docker image, as discussed on [IoT docker matrix.org][2].~~
  See <https://gitlab.com/islandoftex/images/texlive/-/issues/41>.
- [x] ~~Add TeX Live 2024 pretest to the GitHub Actions configuration file.~~
  Added in #406.

 [1]: https://matrix.to/#/!QcHpUHXiiXGXPPXFfh:matrix.org/$mBCAUQNTFIIBoWW7dqxdQ0V6-E8zIG4oI1ttQIZAyk8?via=im.f3l.de&via=matrix.org
 [2]: https://matrix.to/#/!wsMpSBNtefzqhUuyyU:matrix.org/$ep-FO9GpqbuNBBkWBcgXIuf4PVqqpcjq4vpAI3b49mA?via=matrix.org&via=im.f3l.de
 [3]: https://tug.org/texlive/pretest.html
 [4]: https://twitter.com/TeXUsersGroup/status/1756899839768711639
 [5]: https://tug.org/texlive/mirmon/
 [6]: https://tug.org/texlive/
