### ISSUE TITLE
Add support for TeX Live 2024

### ISSUE THREAD

**Issue by Witiko** [Witiko/markdown#411]
At the end of the TeX Live 2024 pretest, we should revert commits e51738ba, 7ef64dd9, and a7cff81d, stop the daily build of [pretest TeX Live Docker image][1] on the `hypnos1` node, and replace the `pretest` image with the `TL2023-historic` image in `.github/workflows/main.yml`.

### Tasks

- [x] ~~Revert e51738ba.~~ Closed in #425.
- [x] ~~Revert 7ef64dd9.~~ Closed in bafbb164.
- [x] ~~Revert a7cff81d.~~ Closed in #413.
- [x] ~~Stop the daily build of [`witiko/texlive-pretest`][1] on `hypnos1`.~~
- [x] ~~Stop building `pretest` images.~~ Closed in 04957eee.
- [x] ~~Start building `TL2023-historic` images.~~ Closed in #425.
- [x] ~~Revert 16000aa4.~~ Closed in #425.
- [x] ~~Revert 9549a5d8.~~ Closed in 844beafc.
- [x] ~~Revert 8f8e1315.~~ Closed in cf592003.

 [1]: https://hub.docker.com/r/witiko/texlive-pretest/tags
