### ISSUE TITLE
Make appending operator more efficient

### ISSUE THREAD

**Issue by Witiko** [Witiko/markdown#437]
In #435, we added support for appending to token renderers and renderer prototypes. However, the current implementation requires an extra token list for each token renderer and renderer prototype that stores a copy of the current definition. This is error-prone, since it silently discards any changes to token renderers and renderer prototypes from outside the `\markdownSetup` command. Furthermore, it is also unnecessary, since we can append directly to the replacement text of token renderers and renderer prototypes as long as the commands are simple unprotected `\def`s with undelimited parameters, as shown [on TeX StackExchange][1] by @eg9, @gucci-on-fleek, @Skillmon and me.

### Tasks

- [x] Define function `\@@_tl_set_from_cs:NNn` following the discussion [on TeX StackExchange][1].
- [x] Remove the extra token list used in appending to token renderers and renderer prototypes.
- [x] Remove error messages `failed-to-append-renderer` and `failed-to-append-renderer-prototype`.
- [x] Acknowledge @eg9 and @gucci-on-fleek in `CHANGES.md`.
- [x] Apply @Skillmon's [suggestions][2] and acknowledge @Skillmon in `CHANGES.md`.
- [x] Document function `\@@_tl_set_from_cs:NNn` in the technical documentation.
- [x] Use the appending operator in the testing framework.

 [1]: https://tex.stackexchange.com/a/716400/70941
 [2]: https://tex.stackexchange.com/questions/716362/convert-control-sequence-with-a-variable-number-of-undelimited-parameters-into-a/716599?noredirect=1#comment1781373_716400

**Comment by Witiko** [comment]
If time permits, we may also want to add the function `\tl_set_from_cs:NN` and its variants discussed [on TeX StackExchange][2] to the l3tl module of [latex3/latex3][1] and open a PR. If merged, we should then mark our function `\@@_tl_set_from_cs:NNn` for removal after we have ceased to support TeX Live 2023.

 [1]: https://github.com/latex3/latex3
 [2]: https://tex.stackexchange.com/a/716400/70941

**Comment by Witiko** [comment]
> We can append directly to the replacement text of token renderers and renderer prototypes as long as the commands are simple unprotected `\def`s with undelimited parameters, as shown [on TeX StackExchange](https://tex.stackexchange.com/a/716400/70941) by @eg9 and me.

There is an open issue with losing one level of `#`s during the round trip from a control sequence to a token list and back, as discussed [on TeX StackExchange](https://tex.stackexchange.com/questions/716362/convert-control-sequence-with-a-variable-number-of-parameters-into-a-token-list/716448#comment1780969_716386).
