### ISSUE TITLE
Support programmatic text in YAML metadata values

### ISSUE THREAD

**Issue by Witiko** [Witiko/markdown#440]
Currently, we assume that all strings in YAML metadata are markdown text. Besides the `jekyllDataString` renderers, we should also produce e.g. `jekyllDataProgrammaticString` renderers, which would receive the raw text of the strings. Furthermore, we should also rename `jekyllDataString` renderers to e.g. `jekyllDataTypographicString` and deprecate the previous name.

### Tasks
- [x] Update unit tests.
- [x] Declare `jekyllDataProgrammaticString` renderer and renderer prototype.
- [x] Produce `jekyllDataProgrammaticString` renderer and renderer prototype.
- [x] Rename `jekyllDataString` renderers and renderer prototypes to `jekyllDataTypographicString`.
- [x] Deprecate `jekyllDataString` similarly to #201.
- [x] Add the changes from this ticket to `CHANGES.md`.
- [x] Acknowledge ISTQB in `CHANGES.md` and  `README.md`.
