### ISSUE TITLE
Citations in lists sometimes cause error `bad argument #2 to 'match' (string expected, got table)`

### ISSUE THREAD

**Issue by Witiko** [Witiko/markdown#460]
Citations in lists sometimes cause error `bad argument #2 to 'match' (string expected, got table)`:

```sh
$ docker run --rm -it witiko/markdown

$ markdown-cli --version
markdown-cli.lua (Markdown) 3.6.1-17-gf57d31e7
Copyright (C) 2009-2016 John MacFarlane, Hans Hagen
Copyright (C) 2016-2024 Vít Starý Novotný, Andrej Genčur
License: LPPL 1.3c

$ markdown-cli citations=true <<-'EOF'
- Color export targets [@latexteam2024interfaces,
  Section 37.8]
EOF

...cal/texlive/texmf-local/tex/luatex/markdown/markdown.lua:4618: bad argument #2 to 'match' (string expected, got table)
```

The full reproducing document originates from https://github.com/Witiko/expltools/pull/3, which is currently blocked by this ticket.

### Tasks

- [x] Add a reproducing test file [`issue-460.test`](https://github.com/Witiko/markdown/blob/fc73190c3aeada647a62f72b3da5c0db687921b8/tests/testfiles/regression/github/issue-460.test) from commit fc73190 in draft PR [#461](https://github.com/Witiko/markdown/pull/461).
- [x] Make the reproducing test file pass the CI.
- [x] Update `CHANGES.md`.
