### ISSUE TITLE
Make `markdown-cli` executable and symlinked to system directories

### ISSUE THREAD

**Issue by Witiko** [Witiko/markdown#534]
### Tasks
- [x] In documentation and `examples/Makefile`, replace `` texlua `kpsewhich markdown-cli.lua` `` with `markdown-cli`.
- [x] In `markdown.dtx`, add `#!/usr/bin/env texlua` to `markdown-cli.lua`.
- [x] In `Makefile`, mark `markdown-cli.lua` as executable both standalone and in the TDS and CTAN ZIP archives.
- [x] In `Dockerfile`, remove the distro `markdown-cli` symlink and create our own instead of the current `markdown-cli` wrapper.
- [x] Add section "Notes to distributors" to `README.md`, as discussed with Z. Wagner and R. Kotucha [at tex-live@tug.org][1].

 [1]: https://tug.org/pipermail/tex-live/2024-December/050952.html
