### ISSUE TITLE
Modernize LaTeX code using xparse and expl3

### ISSUE THREAD

**Issue by Witiko** [Witiko/markdown#96]
At the moment, the LaTeX implementation makes heavy use of the `keyval` and `xstring` third-party packages, and provides unintuitive interface (`\begin{markdown}` and `\begin{markdown*}{options}` instead of `\begin{markdown}` and `\begin{markdown}[options]`).

Instead of using third-party packages, we should modernize the implementation to use `expl3` [for key-value methods instead of `keyval`][3] and [for string comparisons instead of `xstring`][6], and [use `xparse`][4] to provide more intuitive interface (`\begin{markdown}` and `\begin{markdown}[options]` with `\begin{markdown*}{options}` as a deprecated syntax).

## Tasks

- [x] [Use `expl3`][6] to replace calls to [`xstring`][9]. (See #153.)
- [x] [Use `expl3`][3] to replace calls to [`keyval`][10]. (See #157. Check that this closes #130.)
- [ ] ~~[Use `xparse`][4] to add an optional parameter to the `markdown` environment and deprecate the `markdown*` environment.
Use the new form [in `examples/latex.tex`][7].~~ (See #158.)

## References

- [The `expl3` package and LaTeX3 programming][1]
- [Functions and `expl3`][5]
- [Programming key–value in `expl3`][3]
- [The `xparse` package: Document command parser][4]
- [The LaTeX3 Interfaces][2]
- [`xstring`: String manipulation for (La)TeX][9]
- [`keyval`: Process `key=value` schemes][10]

See also other [issues with the `expl3` label][8].

 [1]: https://mirrors.ctan.org/macros/latex/contrib/l3kernel/expl3.pdf
 [2]: https://mirrors.ctan.org/macros/latex/contrib/l3kernel/interface3.pdf
 [3]: https://tug.org/TUGboat/tb31-1/tb97wright-l3keys.pdf
 [4]: http://mirrors.ctan.org/macros/latex/contrib/l3packages/xparse.pdf
 [5]: https://www.tug.org/TUGboat/tb41-3/tb129gregorio-l3functions.pdf
 [6]: https://mirrors.ctan.org/macros/latex/contrib/l3kernel/interface3.pdf#page=131
 [7]: https://github.com/Witiko/markdown/blob/a53489df553c3fa61b6af66f967f64cafafb8895/examples/latex.tex#L54-L71
 [8]: https://github.com/Witiko/markdown/issues?q=label%3Aexpl3+
 [9]: https://www.ctan.org/pkg/xstring
 [10]: https://www.ctan.org/pkg/keyval

**Comment by Witiko** [comment]
This issue is blocked by #124.

**Comment by Witiko** [comment]
This issue closes #96.

**Comment by Witiko** [comment]
This issue is no longer blocked by #124.
